### ISSUE TITLE
Non-malicious traceback in OpenSesame 3.1.3 on Mac

### ISSUE THREAD

**Issue by dschreij** [smathot/QProgEdit#17]
When working with OpenSesame 3.1.3, I see the following traceback in my console, but don't notice any problems in OpenSesame itself at all.

~~~
Traceback (most recent call last):
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/widgets/tree_overview.py", line 314, in mousePressEvent
    target_treeitem.open_tab()
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/qtitem.py", line 122, in open_tab
    self.tabwidget.add(self.widget(), self.item_icon(), self.name)
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/qtitem.py", line 46, in inner
    self.init_edit_widget()
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/sequence.py", line 66, in init_edit_widget
    super(sequence, self).init_edit_widget(False)
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/qtitem.py", line 287, in init_edit_widget
    self._script_widget.addTab(u'Script').setLang(u'OpenSesame')
  File "../smathot/QProgEdit/QProgEdit/_qtabmanager.py", line 124, in addTab
    progEdit = QProgEdit(self, title=title)
  File "../smathot/QProgEdit/QProgEdit/_qprogedit.py", line 65, in __init__
    self.editor = QEditor(self, **editorParams)
  File "../smathot/QProgEdit/QProgEdit/_qeditor.py", line 53, in __init__
    self.setKeyBindings()
  File "../smathot/QProgEdit/QProgEdit/_qeditor.py", line 105, in setKeyBindings
    cmd.setKey(0)
AttributeError: 'NoneType' object has no attribute 'setKey'
~~~

**Comment by smathot** [comment]
Excellent, thanks!
